- // MIR for `simple` before PartialRedundancyElimination
+ // MIR for `simple` after PartialRedundancyElimination
  
  fn simple(_1: i32) -> i32 {
      let mut _0: i32;
      let mut _2: i32;
      let mut _3: i32;
      let mut _4: i32;
      let mut _5: i32;
      let mut _6: i32;
      let mut _7: i32;
  
      bb0: {
          _2 = const 3_i32;
          _3 = const 5_i32;
          _4 = const 10_i32;
          _5 = const 20_i32;
          _6 = const 5_i32;
          _7 = Add(_2, _3);
          _4 = Add(_2, _3);
          _2 = const 10_i32;
          _5 = Add(_2, _3);
          _4 = Add(_2, _3);
          _0 = const 10_i32;
          return;
      }
  }
  
