- // MIR for `simple` before PartialRedundancyElimination
+ // MIR for `simple` after PartialRedundancyElimination
  
  fn simple(_1: i32) -> i32 {
      let mut _0: i32;
      let mut _2: i32;
      let mut _3: i32;
      let mut _4: i32;
  
      bb0: {
          _2 = const 3_i32;
          _3 = const 5_i32;
-         switchInt(_2) -> [3: bb2, otherwise: bb1];
+         switchInt(_2) -> [3: bb3, otherwise: bb1];
      }
  
      bb1: {
          _4 = Add(_2, _3);
          _2 = const 30_i32;
-         goto -> bb2;
+         goto -> bb4;
      }
  
      bb2: {
          _0 = const 10_i32;
          return;
+     }
+ 
+     bb3: {
+         goto -> bb2;
+     }
+ 
+     bb4: {
+         goto -> bb2;
      }
  }
  
